### ISSUE TITLE
Issue in the parentConsent function

### ISSUE THREAD

**Issue by Amogh-4** [gitmarcher/Adios#2]
In the parentConsent function, which is intended to accept parent's images, as a proof for consent, any type of file is getting accepted.

**Comment by gitmarcher** [comment]
Fixed the file upload validation issue by ensuring that only image file types are accepted. The code now checks the MIME type of the uploaded file, and if it does not start with 'image', it throws a 'INVALID_FILE_TYPE' error. This prevents other file types from being accepted.
